[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "code"
version = "0.0.1"
description = "Code utility package"
authors = [
    {name = "hyunjin", email = "leehj0110@kakao.com"}
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["code", "utility"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"
dependencies = [
    "pocketflow>=0.0.3",
]

[project.urls]
Homepage = "https://github.com/hyunjin/hyunjin"
Repository = "https://github.com/hyunjin/hyunjin"

[tool.hatch.build.targets.wheel]
packages = ["code"]

[tool.hatch.version]
path = "code/__init__.py"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0", 
    "pytest-asyncio>=0.21.0",
    "black>=22.0.0",
    "isort>=5.10.0",
    "flake8>=5.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

