/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "ADMIN_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_API_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AWS_SES_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_SES_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_DEFAULT_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Console": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "EMAILOCTOPUS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HONEYCOMB_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "R2AccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "R2SecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "Teams": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "Web": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "WebApp": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "ZEN_BLACK": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS2": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS3": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS4": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS5": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS6": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS7": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "Api": cloudflare.Service
    "AuthApi": cloudflare.Service
    "AuthStorage": cloudflare.KVNamespace
    "Bucket": cloudflare.R2Bucket
    "EnterpriseStorage": cloudflare.R2Bucket
    "GatewayKv": cloudflare.KVNamespace
    "LogProcessor": cloudflare.Service
    "ZenData": cloudflare.R2Bucket
    "ZenDataNew": cloudflare.R2Bucket
  }
}

import "sst"
export {}